feat(routingTable): ajout de la creation table de routage statique
ELDiablO59152/Zigbee-LoRa-Interconnection pull request #11
Opened 2023-05-19 11:45 UTC by PizzISEN

2023-05-19 11:54 UTC, sasah6659 requested changes

2023-05-19 11:54 UTC, sasah6659 commented on Rasp/routingTable/routingTable.json
> +            "comment": "comment"
PublicKey --> ajouter une valeur plutôt que des caractères
comment --> mettre des commentaires utiles

2023-05-19 11:54 UTC, sasah6659 commented on Rasp/routingTable/routingTable.json
> +            "comment": "comment2"
PublicKey --> ajouter une valeur plutôt que des caractères
comment --> mettre des commentaires utiles

2023-05-19 11:54 UTC, sasah6659 commented on Rasp/routingTable/routingTable.json
> +            "comment": "AHAHHAAH"
PublicKey --> ajouter une valeur plutôt que des caractères
comment --> mettre des commentaires utiles plutôt que "AHAHHAAH"

2023-05-19 11:54 UTC, sasah6659 commented on Rasp/routingTable/routingTable.py
> +            routingFile.close()
Pas utile

2023-05-19 11:54 UTC, sasah6659 commented on Rasp/routingTable/routingTable.py
> +            routingFile.close()
Pas utile

2023-05-19 11:54 UTC, sasah6659 commented on Rasp/routingTable/routingTable.py
> +            routingFile.close()
Pas utile

2023-05-19 11:57 UTC, ELDiablO59152 commented on Rasp/routingTable/routingTable.py
> +            routingFile.close()
```suggestion
            with open('routingTable.json','w+') as routingFile:
                jsonFile = json.load(routingFile)
                # Serializing json
                jsonFile["routingTable"].append(routingLine)

                # Sets file's current position at offset.
                routingFile.seek(0)
                json.dump(jsonFile, routingFile, indent = 4)
```

2023-05-19 12:11 UTC, sasah6659 approved these changes

2023-05-22 14:30 UTC, PizzISEN reviewed
All good

2023-05-22 14:30 UTC, merged